CREATE TABLE Teachers (
ID INT PRIMARY KEY NOT NULL,
FirstName NVARCHAR (20) NOT NULL,
LastName NVARCHAR (20)NOT NULL,
DateOfBirth DATE NOT NULL,
AcademicRank NVARCHAR(20) NOT NULL,
HireDate DATE NOT NULL
)